[package]
name = "lesson6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = {version = "0.5.3", features = ["unstable_grab"]}
screenshots = "0.8.5"
chrono = "0.4.31"